baseURL = "https://matthewsm.me"
title = "Matthews"
theme = "custom"
googleAnalytics = "G-DX55PTPFT9"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about"
    weight = 20
