baseURL = "//matthewsm2.github.io/Blog-Site"
title = "Matthews"
theme = "custom"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about"
    weight = 20
